### ISSUE TITLE
Hashrate and aliverate queries take too long

### ISSUE THREAD

**Issue by archangdcc** [Canaan-Creative/Avalon-Management-System#4]
Reason: Table joining is too slow.
Result: these two graphs take too long to load, and will eventually fail on Firefox.

**Comment by archangdcc** [comment]
TODO: Aliverate graph and node hashrate graph.

**Comment by ghost** [comment]
Is this fixed?

**Comment by ghost** [comment]
I guess not. @qinfengling who is working on this?

**Comment by qinfengling** [comment]
@rejon We didn't support this verison now. so I will close the useless issues first.
Thanks for your feedback.
