### ISSUE TITLE
We've got a negative hashrate

### ISSUE THREAD

**Issue by archangdcc** [Canaan-Creative/Avalon-Management-System#5]
![negative](https://cloud.githubusercontent.com/assets/7779694/12548264/0e39297c-c390-11e5-9bbb-1a818c050231.png)

**Comment by archangdcc** [comment]
NTP should be enabled on all the RPis

**Comment by qinfengling** [comment]
The better way is enable it by users. We found some connection issues caused by ntp servers from different region.

**Comment by archangdcc** [comment]
| time | precise_time | total_mh | elapsed | mhs |
| --- | --- | --- | --- | --- |
| 2016-01-21 16:52:01 | 2016-01-04 16:58:03 | 11514084953 | 96 | 119938384.92708333 |
| 2016-01-21 17:07:01 | 2016-01-04 16:58:06 | 7687784661 | 99 | -1275433430.6666667 |

**Comment by archangdcc** [comment]
mhs algorithm:
https://github.com/Canaan-Creative/Avalon-Management-System/blob/master/ams/avalon6.py#L531

**Comment by archangdcc** [comment]
NTP should always be opened on AMS farms.
