### ISSUE TITLE
A7 branch cann't support A741

### ISSUE THREAD

**Issue by qinfengling** [Canaan-Creative/Avalon-Management-System#7]
@archangdcc A741 has 22 x 4 asics, but A721 only has 18 x 4 asics. So should we add a new file Avalon741.py to support it? And suggestions?

**Comment by archangdcc** [comment]
No need to add a new file.
Add some new columns in the module table and leave them blank for A721.

**Comment by archangdcc** [comment]
Branch a7 merged to master.

Use this script to update mysql tables:
https://github.com/Canaan-Creative/Avalon-Management-System/tree/master/server/mysql-update
